#!/bin/bash

SCRIPTS_DIR=$(realpath "$( dirname -- "${BASH_SOURCE[0]}" )")
REPO_ROOT=$(realpath "${SCRIPTS_DIR}/../")

CONTAINER_IMG=ubuntu
CONTAINER_PATH=/ga
CONTAINER_NAME=ga-test

docker run --name "${CONTAINER_NAME}" --volume "${REPO_ROOT}":"${CONTAINER_PATH}" -d -i -t "${CONTAINER_IMG}" /bin/bash
docker exec -t "${CONTAINER_NAME}" "${CONTAINER_PATH}/scripts/ubuntu_deps_setup"
docker exec -t "${CONTAINER_NAME}" pytest "${CONTAINER_PATH}"

STATUS=$?

docker kill "${CONTAINER_NAME}"
docker rm "${CONTAINER_NAME}"

exit ${STATUS}

