name: QA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: apt
        run: |
          sudo apt update -y
          DEBIAN_FRONTEND=noninteractive sudo apt install -y \
            python3-pip flake8
      - name: pip
        run: |
          sudo pip3 install qmp pytest mock
      - run: sudo pytest -vvv test
      - run: pytest -vvv misc
      - name: flake8 src
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      - name: flake8 test
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 test --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 test --count --max-complexity=10 --max-line-length=127 --statistics
      - name: flake8 misc
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 misc --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 misc --count --max-complexity=10 --max-line-length=127 --statistics

